# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.assessments_api import AssessmentsApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestAssessmentsApi(unittest.TestCase):
    """AssessmentsApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.assessments_api.AssessmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_assignable_assessments(self):
        """Test case for get_user_assignable_assessments

        Retrieves a paginated list of assignable assessments for the user corresponding to the username provided  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
