# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.assignments_api import AssignmentsApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestAssignmentsApi(unittest.TestCase):
    """AssignmentsApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.assignments_api.AssignmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_assignments_for_user(self):
        """Test case for create_assignments_for_user

        Assigns multiple assessments to one user  # noqa: E501
        """
        pass

    def test_get_user_assignments(self):
        """Test case for get_user_assignments

        Retrieves a paginated list of assignments for the provided username  # noqa: E501
        """
        pass

    def test_get_users_behavioral_assignment(self):
        """Test case for get_users_behavioral_assignment

        Retrieves behavioral assignment results for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_behavioral_assignment_result_pdf(self):
        """Test case for get_users_behavioral_assignment_result_pdf

        Retrieves a behavioral assignment results pdf for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_clinical_assignment(self):
        """Test case for get_users_clinical_assignment

        Retrieves clinical assignment results for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_clinical_assignment_result_pdf(self):
        """Test case for get_users_clinical_assignment_result_pdf

        Retrieves a clinical assignment results pdf for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_self_assignment(self):
        """Test case for get_users_self_assignment

        Retrieves self assignment results for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_self_assignment_result_pdf(self):
        """Test case for get_users_self_assignment_result_pdf

        Retrieves a self assignment results pdf for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_situational_assignment(self):
        """Test case for get_users_situational_assignment

        Retrieves a situational assignment results for a provided username and assignment ID  # noqa: E501
        """
        pass

    def test_get_users_situational_assignment_result_pdf(self):
        """Test case for get_users_situational_assignment_result_pdf

        Retrieves a situational assignment results pdf for a provided username and assignment ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
