# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import unittest

from test.helpers.vcr import vcr

import relias_api_client
from relias_api_client.api.applicants_api import ApplicantsApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestApplicantsApi(unittest.TestCase):
    """ApplicantsApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.applicants_api.ApplicantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_to_learner(self):
        """Test case for convert_to_learner

        Converts an applicant based on the username provided to a learner with the new username supplied  # noqa: E501
        """
        pass

    @vcr.use_cassette
    def test_create_applicant(self):
        """Test case for create_applicant

        Creates an applicant with the supplied information  # noqa: E501
        """

        new_applicant = relias_api_client.models.create_applicant_request.CreateApplicantRequest(
            first_name="Jim",
            last_name="Morrison",
            email="jim@dka.im",
            guid="EGL9711",
            org_id=relias_api_client.Configuration().org_id,
            tracking_id="EGL9711"
        )
        api_client = relias_api_client.ApplicantsApi()
        result = api_client.create_applicant(new_applicant)
        self.assertTrue(result.active)
        self.assertIsNotNone(result.applicant_id)
        self.assertEqual(result.guid, new_applicant.guid)
        self.assertEqual(result.tracking_id, new_applicant.tracking_id)
        self.assertEqual(result.user_name, new_applicant.email)


    def test_get_applicant(self):
        """Test case for get_applicant

        Retrieves an applicant based on the username provided  # noqa: E501
        """
        pass

    def test_update_applicant(self):
        """Test case for update_applicant

        Update an applicant using JSON patch documents.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
