# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.bundles_api import BundlesApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestBundlesApi(unittest.TestCase):
    """BundlesApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.bundles_api.BundlesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_matching_bundles_by_profile(self):
        """Test case for matching_bundles_by_profile

        Returns user's Matching Bundles by Profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
