# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.users_api import UsersApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Creates a user with the supplied information  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Retrieves a user based on the username provided  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user using JSON patch documents.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
