# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.models.job_title_model import JobTitleModel  # noqa: E501
from relias_api_client.rest import ApiException


class TestJobTitleModel(unittest.TestCase):
    """JobTitleModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobTitleModel(self):
        """Test JobTitleModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = relias_api_client.models.job_title_model.JobTitleModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
