# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.webhooks_api import WebhooksApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_assignment_completed_webhook(self):
        """Test case for create_assignment_completed_webhook

        Creates the Assignment Completed Webhook with the supplied Callback URL and optional authentication information  # noqa: E501
        """
        pass

    def test_delete_assignment_completed_webhook(self):
        """Test case for delete_assignment_completed_webhook

        Deletes the Assignment Completed Webhook  # noqa: E501
        """
        pass

    def test_get_assignment_completed_webhook(self):
        """Test case for get_assignment_completed_webhook

        Retrieves the Assignment Completed Webhook  # noqa: E501
        """
        pass

    def test_update_assignment_completed_webhook(self):
        """Test case for update_assignment_completed_webhook

        Updates the Assignment Completed Webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
