# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.locations_api import LocationsApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.locations_api.LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_locations(self):
        """Test case for get_locations

        Retrieves a paginated list of locations for the current user's organization or provided org ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
