# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import relias_api_client
from relias_api_client.api.departments_api import DepartmentsApi  # noqa: E501
from relias_api_client.rest import ApiException


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self):
        self.api = relias_api_client.api.departments_api.DepartmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_departments(self):
        """Test case for get_departments

        Retrieves a paginated list of departments for the current user's organization or provided org ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
