# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from relias_api_client.configuration import Configuration


class CreateUserResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'int',
        'org_id': 'int',
        'first_name': 'str',
        'last_name': 'str',
        'user_name': 'str',
        'email': 'str',
        'learner_id': 'str',
        'active': 'bool',
        'guid': 'str'
    }

    attribute_map = {
        'user_id': 'userId',
        'org_id': 'orgId',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'user_name': 'userName',
        'email': 'email',
        'learner_id': 'learnerId',
        'active': 'active',
        'guid': 'guid'
    }

    def __init__(self, user_id=None, org_id=None, first_name=None, last_name=None, user_name=None, email=None, learner_id=None, active=None, guid=None, _configuration=None):  # noqa: E501
        """CreateUserResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._user_id = None
        self._org_id = None
        self._first_name = None
        self._last_name = None
        self._user_name = None
        self._email = None
        self._learner_id = None
        self._active = None
        self._guid = None
        self.discriminator = None

        if user_id is not None:
            self.user_id = user_id
        if org_id is not None:
            self.org_id = org_id
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if user_name is not None:
            self.user_name = user_name
        if email is not None:
            self.email = email
        if learner_id is not None:
            self.learner_id = learner_id
        if active is not None:
            self.active = active
        if guid is not None:
            self.guid = guid

    @property
    def user_id(self):
        """Gets the user_id of this CreateUserResponse.  # noqa: E501


        :return: The user_id of this CreateUserResponse.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this CreateUserResponse.


        :param user_id: The user_id of this CreateUserResponse.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def org_id(self):
        """Gets the org_id of this CreateUserResponse.  # noqa: E501


        :return: The org_id of this CreateUserResponse.  # noqa: E501
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this CreateUserResponse.


        :param org_id: The org_id of this CreateUserResponse.  # noqa: E501
        :type: int
        """

        self._org_id = org_id

    @property
    def first_name(self):
        """Gets the first_name of this CreateUserResponse.  # noqa: E501


        :return: The first_name of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this CreateUserResponse.


        :param first_name: The first_name of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this CreateUserResponse.  # noqa: E501


        :return: The last_name of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this CreateUserResponse.


        :param last_name: The last_name of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def user_name(self):
        """Gets the user_name of this CreateUserResponse.  # noqa: E501


        :return: The user_name of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this CreateUserResponse.


        :param user_name: The user_name of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._user_name = user_name

    @property
    def email(self):
        """Gets the email of this CreateUserResponse.  # noqa: E501


        :return: The email of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CreateUserResponse.


        :param email: The email of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def learner_id(self):
        """Gets the learner_id of this CreateUserResponse.  # noqa: E501


        :return: The learner_id of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._learner_id

    @learner_id.setter
    def learner_id(self, learner_id):
        """Sets the learner_id of this CreateUserResponse.


        :param learner_id: The learner_id of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._learner_id = learner_id

    @property
    def active(self):
        """Gets the active of this CreateUserResponse.  # noqa: E501


        :return: The active of this CreateUserResponse.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this CreateUserResponse.


        :param active: The active of this CreateUserResponse.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def guid(self):
        """Gets the guid of this CreateUserResponse.  # noqa: E501


        :return: The guid of this CreateUserResponse.  # noqa: E501
        :rtype: str
        """
        return self._guid

    @guid.setter
    def guid(self, guid):
        """Sets the guid of this CreateUserResponse.


        :param guid: The guid of this CreateUserResponse.  # noqa: E501
        :type: str
        """

        self._guid = guid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateUserResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateUserResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateUserResponse):
            return True

        return self.to_dict() != other.to_dict()
