# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from relias_api_client.configuration import Configuration


class GetAssignmentCompletedWebhookResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'webhook_id': 'int',
        'org_id': 'int',
        'callback_url': 'str',
        'username': 'str'
    }

    attribute_map = {
        'webhook_id': 'webhookId',
        'org_id': 'orgId',
        'callback_url': 'callbackUrl',
        'username': 'username'
    }

    def __init__(self, webhook_id=None, org_id=None, callback_url=None, username=None, _configuration=None):  # noqa: E501
        """GetAssignmentCompletedWebhookResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._webhook_id = None
        self._org_id = None
        self._callback_url = None
        self._username = None
        self.discriminator = None

        if webhook_id is not None:
            self.webhook_id = webhook_id
        if org_id is not None:
            self.org_id = org_id
        if callback_url is not None:
            self.callback_url = callback_url
        if username is not None:
            self.username = username

    @property
    def webhook_id(self):
        """Gets the webhook_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501


        :return: The webhook_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :rtype: int
        """
        return self._webhook_id

    @webhook_id.setter
    def webhook_id(self, webhook_id):
        """Sets the webhook_id of this GetAssignmentCompletedWebhookResponse.


        :param webhook_id: The webhook_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :type: int
        """

        self._webhook_id = webhook_id

    @property
    def org_id(self):
        """Gets the org_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501


        :return: The org_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this GetAssignmentCompletedWebhookResponse.


        :param org_id: The org_id of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :type: int
        """

        self._org_id = org_id

    @property
    def callback_url(self):
        """Gets the callback_url of this GetAssignmentCompletedWebhookResponse.  # noqa: E501


        :return: The callback_url of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :rtype: str
        """
        return self._callback_url

    @callback_url.setter
    def callback_url(self, callback_url):
        """Sets the callback_url of this GetAssignmentCompletedWebhookResponse.


        :param callback_url: The callback_url of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :type: str
        """

        self._callback_url = callback_url

    @property
    def username(self):
        """Gets the username of this GetAssignmentCompletedWebhookResponse.  # noqa: E501


        :return: The username of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this GetAssignmentCompletedWebhookResponse.


        :param username: The username of this GetAssignmentCompletedWebhookResponse.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetAssignmentCompletedWebhookResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetAssignmentCompletedWebhookResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetAssignmentCompletedWebhookResponse):
            return True

        return self.to_dict() != other.to_dict()
