# coding: utf-8

"""
    Relias API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from relias_api_client.configuration import Configuration


class MatchingProfileResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'due_date_in_days_after_assignment': 'int',
        'attributes': 'list[str]'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'due_date_in_days_after_assignment': 'dueDateInDaysAfterAssignment',
        'attributes': 'attributes'
    }

    def __init__(self, title=None, description=None, due_date_in_days_after_assignment=None, attributes=None, _configuration=None):  # noqa: E501
        """MatchingProfileResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._title = None
        self._description = None
        self._due_date_in_days_after_assignment = None
        self._attributes = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if due_date_in_days_after_assignment is not None:
            self.due_date_in_days_after_assignment = due_date_in_days_after_assignment
        if attributes is not None:
            self.attributes = attributes

    @property
    def title(self):
        """Gets the title of this MatchingProfileResponse.  # noqa: E501


        :return: The title of this MatchingProfileResponse.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MatchingProfileResponse.


        :param title: The title of this MatchingProfileResponse.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this MatchingProfileResponse.  # noqa: E501


        :return: The description of this MatchingProfileResponse.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MatchingProfileResponse.


        :param description: The description of this MatchingProfileResponse.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def due_date_in_days_after_assignment(self):
        """Gets the due_date_in_days_after_assignment of this MatchingProfileResponse.  # noqa: E501


        :return: The due_date_in_days_after_assignment of this MatchingProfileResponse.  # noqa: E501
        :rtype: int
        """
        return self._due_date_in_days_after_assignment

    @due_date_in_days_after_assignment.setter
    def due_date_in_days_after_assignment(self, due_date_in_days_after_assignment):
        """Sets the due_date_in_days_after_assignment of this MatchingProfileResponse.


        :param due_date_in_days_after_assignment: The due_date_in_days_after_assignment of this MatchingProfileResponse.  # noqa: E501
        :type: int
        """

        self._due_date_in_days_after_assignment = due_date_in_days_after_assignment

    @property
    def attributes(self):
        """Gets the attributes of this MatchingProfileResponse.  # noqa: E501


        :return: The attributes of this MatchingProfileResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this MatchingProfileResponse.


        :param attributes: The attributes of this MatchingProfileResponse.  # noqa: E501
        :type: list[str]
        """

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchingProfileResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchingProfileResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchingProfileResponse):
            return True

        return self.to_dict() != other.to_dict()
